Repository eclipse-tractusx/tractusx-quality-checks, pull requests merged in 2023-07, with the labels that each got.

#25 chore: update repository metadata
  .tractusx
Labels: skip-changelog, chore, patch

#30 chore: update workflow trigger for pull request
  .github/workflows/release-drafter.yaml
Labels: chore, patch

#35 fix: auto-pass default branch check on forks
  internal/repo/default_branch.go
  pkg/repo/repoinfo.go
Labels: bug, patch

#29 chore: update dependencies due to CVE-2023-1732
  DEPENDENCIES
  go.mod
  go.sum
Labels: chore, patch

#37 fix: correct temurin docker image name for base image check
  internal/container/allowed_base_image_check.go
  internal/container/allowed_base_image_check_test.go
Labels: bug, patch
