Repository eclipse-tractusx/tractusx-quality-checks, pull requests merged in 2023-11, with the labels that each got.

#63 feat: skip aligned base image check based on metadata config
  docs/README.md
  docs/metadata_file.md
  internal/filesystem/filesystem_test.go
  pkg/container/allowed_base_image_check.go
  pkg/container/allowed_base_image_check_test.go
  pkg/container/dockerfile.go
  pkg/container/dockerfile_test.go
  pkg/helm/helmchart_structure_exists.go
  pkg/helm/helmchart_structure_exists_test.go
  pkg/helm/resource_mgmt_check_test.go
  pkg/repo/repo_structure_exists_test.go
  pkg/repo/repoinfo.go
  pkg/tractusx/metadata.go
  pkg/tractusx/metadata_test.go
  pkg/tractusx/test/metadata_test_template.yaml
  pkg/tractusx/types.go
Labels: documentation, enhancement, minor

#64 chore: add files and folders to gitignore
  .gitignore
Labels: chore, patch

#65 feat: env variable to set basedir for checkLocal
  cmd/checkLocal.go
Labels: enhancement, minor
