Repository eclipse-tractusx/tractusx-quality-checks, pull requests merged in 2023-10, with the labels that each got.

#51 chore: add alpine as allowed base image
  pkg/container/allowed_base_image_check.go
Labels: chore, patch

#54 fix: add platform input to the gh action
  action.yaml
Labels: bug, patch

#55 feat: add non root container check
  DEPENDENCIES
  cmd/checkLocal.go
  go.mod
  go.sum
  pkg/container/allowed_base_image_check_test.go
  pkg/container/dockerfile.go
  pkg/container/non_root_container_check.go
  pkg/container/non_root_container_check_test.go
Labels: enhancement, minor

#57 chore(deps): update DEPENDENCIES with latest info
  DEPENDENCIES
Labels: chore, patch

#58 chore(build): run dash license check on each PR
  .github/workflows/dash-licence-check.yaml
Labels: chore, patch

#56 feat: web format errors
  pkg/container/allowed_base_image_check.go
  pkg/helm/helmchart_structure_exists.go
  pkg/tractusx/types.go
Labels: enhancement, minor

#61 chore(build): add workflow to run unit tests on PR
  .github/workflows/unit-test-pr.yaml
Labels: chore, patch

#59 chore: helm pkg enhancement
  cmd/checkLocal.go
  internal/helm/chartyaml.go
  pkg/container/non_root_container_check.go
  pkg/container/non_root_container_check_test.go
  pkg/helm/helmchart_structure_exists.go
Labels: chore, patch

#62 chore: remove unnecessary function parameter
  pkg/container/allowed_base_image_check.go
Labels: chore, patch
